
# bootstrap
shap_list = ['wind_speed',
 'track_distance',
 'rainfall_max_6h',
 'percent_houses_damaged_5years',
 'rainfall_max_24h',
 'coast_length',
 'mean_elev',
 'urban',
 'mean_slope',
 'total_houses',
 'rwi',
 'std_tri',
 'rural',
 'std_slope',
 'total_pop',
 'mean_tri',
 'water',
 'with_coast']

# boostrap
shap_list_xgb2 = ['wind_speed',
 'track_distance',
 'rainfall_max_6h',
 'percent_houses_damaged_5years',
 'rainfall_max_24h',
 'mean_elev',
 'urban',
 'mean_slope',
 'coast_length',
 'mean_tri',
 'std_slope',
 'rwi',
 'rural',
 'std_tri',
 'total_houses',
 'total_pop',
 'water',
 'with_coast']

# bootstrap
lime_list = ['wind_speed',
 'track_distance',
 'rwi',
 'rainfall_max_6h',
 'percent_houses_damaged_5years',
 'rainfall_max_24h',
 'total_pop',
 'coast_length',
 'urban',
 'rural',
 'total_houses',
 'mean_elev',
 'mean_slope',
 'std_tri',
 'water',
 'with_coast',
 'std_slope',
 'mean_tri'] 

# bootstrap
lime_list_xgb2 = ['wind_speed',
 'track_distance',
 'rwi',
 'percent_houses_damaged_5years',
 'rainfall_max_6h',
 'rainfall_max_24h',
 'total_pop',
 'coast_length',
 'urban',
 'rural',
 'mean_elev',
 'total_houses',
 'mean_tri',
 'mean_slope',
 'std_tri',
 'water',
 'std_slope',
 'with_coast',]

# checked
xgb_list = ['wind_speed',
 'track_distance',
 'rainfall_max_24h',
 'percent_houses_damaged_5years',
 'rural',
 'mean_tri',
 'mean_slope',
 'std_tri',
 'with_coast',
 'rainfall_max_6h',
 'mean_elev',
 'std_slope',
 'rwi',
 'total_pop',
 'water',
 'coast_length',
 'total_houses',
 'urban']

check = "check_0624_2"