shap_list = ['wind_speed', 'track_distance', 'rainfall_max_6h',
       'percent_houses_damaged_5years', 'rainfall_max_24h', 'urban',
       'mean_elev', 'coast_length', 'total_houses', 'rwi', 'std_slope',
       'mean_slope', 'total_pop', 'mean_tri', 'water', 'rural', 'std_tri',
       'with_coast']

shap_list_xgb2 = ['wind_speed', 'track_distance', 'percent_houses_damaged_5years',
       'rainfall_max_6h', 'rainfall_max_24h', 'mean_elev', 'mean_slope',
       'coast_length', 'rural', 'total_houses', 'std_tri', 'urban',
       'std_slope', 'mean_tri', 'rwi', 'total_pop', 'water', 'with_coast']

lime_list = ['wind_speed',
 'track_distance',
 'rwi',
 'rainfall_max_6h',
 'percent_houses_damaged_5years',
 'rainfall_max_24h',
 'urban',
 'mean_elev',
 'coast_length',
 'rural',
 'std_slope',
 'total_pop',
 'water',
 'mean_tri',
 'total_houses',
 'std_tri',
 'with_coast',
 'mean_slope']

lime_list_xgb2 = ['wind_speed',
 'track_distance',
 'rwi',
 'rainfall_max_6h',
 'percent_houses_damaged_5years',
 'rainfall_max_24h',
 'total_pop',
 'coast_length',
 'urban',
 'rural',
 'total_houses',
 'mean_slope',
 'mean_elev',
 'std_tri',
 'mean_tri',
 'water',
 'std_slope',
 'with_coast']


xgb_list = ['wind_speed',
              'std_tri',
              'track_distance',
              'with_coast',
              'rainfall_max_24h',
              'mean_tri',
              'percent_houses_damaged_5years',
              'rainfall_max_6h',
              'mean_slope',
              'std_slope',
              'total_pop',
              'mean_elev',
              'water',
              'total_houses',
              'rural',
              'rwi',
              'coast_length',
              'urban']